name: Schedule Weekly Meeting

on:
  schedule:
    - cron: '* * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        run: |
          curl -X POST https://your-render-url.com/schedule-weekly-meeting/ \
               -H "Authorization: Bearer AUTOMATED1MEETING2SCHEDULER"
