name: Schedule Weekly Meeting

on:
  schedule:
    - cron: '30 15 * * 6'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Make HTTP request
        run: |
          curl -X POST https://automated-meeting-schedular.onrender.com/schedule-weekly-meeting/ \
               -H "Authorization: Bearer AUTOMATED1MEETING2SCHEDULER"
